"""add_period_and_memo_to_payitem

Revision ID: 2d3329f135f3
Revises: 35f0480142c0
Create Date: 2025-08-10 19:52:47.949096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3329f135f3'
down_revision: Union[str, Sequence[str], None] = '35f0480142c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pay_item', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('pay_item', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('pay_item', sa.Column('memo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay_item', 'memo')
    op.drop_column('pay_item', 'period_end')
    op.drop_column('pay_item', 'period_start')
    # ### end Alembic commands ###
