"""reconcile tables + payitem ext id

Revision ID: 43e6d83c7f7e
Revises: 9013c5456655
Create Date: 2025-08-10 17:36:51.088558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e6d83c7f7e'
down_revision: Union[str, Sequence[str], None] = '9013c5456655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('employee_ext_id', sa.String(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('contribution_pct', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ach_transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('file_ref', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('employee_ext_id', sa.String(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('expected_pct', sa.Float(), nullable=True),
    sa.Column('actual_pct', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pay_item', sa.Column('employee_ext_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pay_item', 'employee_ext_id')
    op.drop_table('reconciliation_item')
    op.drop_table('ach_transfer')
    op.drop_table('reconciliation_run')
    op.drop_table('enrollment')
    # ### end Alembic commands ###
