"""add_reconciliation_insights_table

Revision ID: a0f60853b0be
Revises: ec8f5daf0299
Create Date: 2025-08-10 23:22:01.917467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0f60853b0be'
down_revision: Union[str, Sequence[str], None] = 'ec8f5daf0299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('top_causes', sa.JSON(), nullable=True),
    sa.Column('total_impact', sa.Float(), nullable=True),
    sa.Column('affected_employees', sa.Integer(), nullable=True),
    sa.Column('suggested_fixes', sa.Text(), nullable=True),
    sa.Column('priority_actions', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['reconciliation_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_insights_tenant_id'), 'reconciliation_insights', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_insights_tenant_id'), table_name='reconciliation_insights')
    op.drop_table('reconciliation_insights')
    # ### end Alembic commands ###
