name: api
on:
  push:
    paths: ["app/**", ".github/workflows/api.yml"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          cd app
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t sitepkg
          cp -r * sitepkg/
          cd sitepkg
          zip -r ../api.zip .
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to App Service
        run: |
          az webapp deploy --name payfast-api --resource-group rg-payfast-dev --src-path app/api.zip --type zip